language: python
python: 
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install -r dev-requirements.txt --use-mirrors"
    - pip install coveralls --use-mirrors
    - ./manage.py syncdb --noinput
    - python setup.py develop
script: "py.test --cov . ."
after_success:
    - coveralls
notifications:
    irc:
        channels: "irc.freenode.org#hacklab/"
        use_notice: true
    email:
        - "santagada@hacklab.com.br"
