language: python
python:
    - "2.7"
node_js:
    - "0.10"
install:
    - "pip install -q -r requirements.txt --use-mirrors"
    - "pip install -q -r dev-requirements.txt --use-mirrors"
    - "pip install -q coveralls --use-mirrors"
    - "npm install less yuglify karma --loglevel silent"
    - "python setup.py -q develop"
    - "./manage.py syncdb --noinput"
script:
    - "./all_tests.sh"
after_success:
    - coveralls
notifications:
    irc:
        channels: "irc.freenode.org#hacklab/"
        use_notice: true
        on_success: change
        on_failure: always
    email:
        recipients:
            - "timtec-dev@listas.hacklab.com.br"
        on_success: change
        on_failure: always
